// web_admin_panel/pubspec.yaml
name: web_admin_panel
version: 1.0.0+1
description: Flutter Web Admin Panel for Bus Booking App
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  pdf: ^3.10.7
  printing: ^5.12.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
